kind: ServiceAccount
apiVersion: v1
metadata:
  name: voting
  namespace: emojivoto
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: voting
  namespace: emojivoto
  labels:
    app.kubernetes.io/name: voting
    app.kubernetes.io/part-of: emojivoto
    app.kubernetes.io/version: v1
spec:
  serviceName: "voting"
  replicas: 1
  selector:
    matchLabels:
      app: voting-svc
      version: v1
  template:
    metadata:
      labels:
        app: voting-svc
        version: v1
    spec:
      serviceAccountName: voting
      containers:
      - env:
        - name: EDG_MARBLE_COORDINATOR_ADDR
          value: coordinator-mesh-api.marblerun:25554
        - name: EDG_MARBLE_TYPE
          value: voting-svc
        - name: EDG_MARBLE_DNS_NAMES
          value: "voting-svc,voting-svc.emojivoto,voting-svc.emojivoto.svc.cluster.local"
        - name: EDG_MARBLE_UUID_FILE
          value: "/voting-svc/data/uuid"
        - name: OE_SIMULATION
          valueFrom:
            configMapKeyRef:
              name: oe-config
              key: OE_SIMULATION
        image: {{ .Values.voting.image }}:{{ .Values.voting.imageVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        name: voting-svc
        ports:
        - containerPort: 8080
          name: grpc
        - containerPort: 8801
          name: prom
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: voting-data
          mountPath: /voting-svc/data
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
  - metadata:
      name: voting-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Mi
---
apiVersion: v1
kind: Service
metadata:
  name: voting-svc
  namespace: emojivoto
spec:
  selector:
    app: voting-svc
  ports:
  - name: grpc
    port: 8080
    targetPort: 8080
  - name: prom
    port: 8801
    targetPort: 8801
