imagePullSecrets:
  - name: regcred

simulation:
  OE_SIMULATION: "1"

web:
  image: ghcr.io/edgelesssys/emojivoto/web
  imageVersion: v0.2.0
  # add your host to the list
  hosts: "localhost"

emoji:
  image: ghcr.io/edgelesssys/emojivoto/emoji-svc
  imageVersion: v0.2.0

voting:
  image: ghcr.io/edgelesssys/emojivoto/voting-svc
  imageVersion: v0.2.0
