imagePullSecrets:
  - name: regcred

imagePullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m
  limits:
    kubernetes.azure.com/sgx_epc_mem_in_MiB: 10

tolerations:
- key: kubernetes.azure.com/sgx_epc_mem_in_MiB
operator: Exists
effect: NoSchedule

simulation:
  OE_SIMULATION: "0"

web:
  image: ghcr.io/edgelesssys/emojivoto/web
  imageVersion: v0.2.0

emoji:
  image: ghcr.io/edgelesssys/emojivoto/emoji-svc
  imageVersion: v0.2.0

voting:
  image: ghcr.io/edgelesssys/emojivoto/voting-svc
  imageVersion: v0.2.0

