imagePullSecrets:
  - name: regcred

resources:
  requests:
    cpu: 100m
  limits:
    kubernetes.azure.com/sgx_epc_mem_in_MiB: 10

tolerations:
- key: kubernetes.azure.com/sgx_epc_mem_in_MiB
operator: Exists
effect: NoSchedule

simulation:
  OE_SIMULATION: "0"

# add your host to the list
hosts: "localhost"

