imagePullSecrets:
  - name: regcred

imagePullPolicy: IfNotPresent

resources:
  requests:
    cpu: 100m

simulation:
  OE_SIMULATION: "0"

web:
  image: local/emojivoto/web
  imageVersion: devel
  tlsServer: enabled

emoji:
  image: local/emojivoto/emoji-svc
  imageVersion: devel

voting:
  image: local/emojivoto/voting-svc
  imageVersion: devel

